title: "[From➡️To] "
body:
  - type: dropdown
    attributes:
      label: 구분
      options:
        - 통신 일정
        - 통신 과정
        - 진행 상황
        - 기타
  - type: markdown
    attributes:
      value: |
        ## 이슈 사항
  - type: textarea
    attributes:
      id: issue
      description: 이슈 사항
      value: |
        1. text
        2. text
        * text
      render: markdown

