title: "[From➡️To] "
body:
  - type: dropdown
    attributes:
      label: 구분
      options:
        - 통신 일정
        - 통신 과정
        - 진행 상황
        - 기타
   - type: input
    id: has-id
    attributes:
      label: 제안 사항
    validations:
      required: true
        # ### 제안 사항
        # * text
        # * text
        # ### 첨부 코드
        # ```cs
        # code
        # ```

