title: "[Bug]: "
body:
- type: markdown
  value: "## Welcome!"
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to start a new discussion! If you need real-time help, join us on Discord.
