title: "[From➡️To] "
body:
  - type: dropdown
    attributes:
      label: 구분
      options:
        - 통신 일정
        - 통신 과정
        - 진행 상황
        - 기타
  - type: markdown
    attributes:
      value: |      
        ### 이슈 사항
        * text
        * text
        ### 제안 사항
        * text
        * text
        ### 첨부 코드
        ```cs
        code
        ```

