title: "[From➡️To]  "
body:
- type: textarea
  attributes:
    label: 전달 사항
    value: |
      ## 카테고리: ex. 통신, 코드 수정, 요청사항
      * text
      * text
      * text
- type: textarea
  attributes:
    label: 요청 사항
    value: |
      * text
      * text
      * text
- type: textarea
  attributes:
    label: 첨부 코드
    value: |
      ```cs
      code
      ```
